name: PHPStan

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    phpstan:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
                php-versions: ['7.1', '7.2', '7.3', '7.4']
        name: PHP ${{ matrix.php-versions }}, ${{ matrix.operating-system }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   name: Install composer dependencies
                run: composer install --prefer-dist --no-interaction --no-progress

            -   name: Run PHPStan
                run: composer stan
